#
# scientific-computing Dockerfile
#
# https://github.com/ibbd/dockerfile-python/python2/scientific-computing
#
# sudo docker build -t ibbd/scientific-computing ./
#

# Pull base image.
FROM ibbd/python

MAINTAINER Alex Cai "cyy0523xc@gmail.com"



